Fix assertion
apache/maven-dependency-plugin pull request #447
Opened 2024-10-17 11:54 UTC by elharo

This test could never fail

2024-10-22 08:12 UTC, michael-o reviewed
I honestly don't udnerstand why this is needed at all. I mean we have `-q` and `-X`...

2024-10-22 14:32 UTC, michael-o commented
> Yes, I'm not sure why this was done like this in the first place. This has been around since 2.0 so who knows? I am confident the way it was done is buggy, so this tries to repair as much of it as I easily could. I noticed because the tests mixed up two different silent log classes. Someone wasn't following test first practices when they wrote this.
> 
> If we're comfortable with some incompatibility, then we could mke the silent parameter and associated methods noops.

Maybe we should deprecate for removal in 4?

2024-10-22 19:41 UTC, elharo commented
OK, deprecated

2024-10-22 19:42 UTC, elharo reviewed
Oh dman it, that went to the wrong branch. Why, why don't we protect our branches?

2024-11-07 20:12 UTC, elharo commented
Ping

2024-11-09 13:06 UTC, michael-o requested changes

2024-11-09 13:06 UTC, michael-o commented on src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
> +     * @deprecated to be removed in 4.0; use -Q command line option instead
`-q`, not `-Q`

2024-11-09 13:06 UTC, michael-o commented on src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
> +     * @deprecated to be removed in 4.0; no API replacement, use -Q command line option instead
same here

2024-11-09 13:33 UTC, elharo commented on src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
> +     * @deprecated to be removed in 4.0; use -Q command line option instead
done

2024-11-09 13:33 UTC, elharo commented on src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
> +     * @deprecated to be removed in 4.0; no API replacement, use -Q command line option instead
done

2024-11-09 13:38 UTC, michael-o approved these changes

2024-11-09 15:12 UTC, merged

2025-06-18 08:10 UTC, jira-importer commented
Resolve #1455