Elaborate on DependencyUtil.log in doc comment
apache/maven-dependency-plugin pull request #449
Opened 2024-10-18 11:58 UTC by elharo

This method initially confused me, so once I figured out what it was doing I added a comment. No bheavioral changes.

2024-10-19 14:58 UTC, michael-o requested changes
A few typos also in the commit message

2024-10-19 14:58 UTC, michael-o commented on src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
> +     * {@code DependencyUtil.log(s, log)} and {@code log.indfo(s)} is that the latter
Typo

2024-10-19 15:55 UTC, elharo commented on src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
> +     * {@code DependencyUtil.log(s, log)} and {@code log.indfo(s)} is that the latter
fixed

2024-10-22 19:43 UTC, michael-o approved these changes

2024-10-23 13:10 UTC, merged